### ISSUE TITLE
watch stops working after 1st save

### ISSUE THREAD

**Issue by jhartman86** [tockins/realize#149]
The watcher seems to stop working after the first time a file gets saved, **until** another file gets saved. The app doesn't crash or exit; and the watcher _does_ continue running - but it won't restart/do-whatever-is-configured.

Here's what happens exactly: say files A.go and B.go exist. Realize has started and completed a build for the first time. File A gets changed and saved, and realize detects its and runs a build. Another change is made to file A and saved - _realize doesn't do anything_. If you edit file B and save it, realize will detect and run a build. Now if you go back and change file A again and save it, realize runs again. So on and so forth.

It feels like some kind of caching mechanism against the filename might be causing issues, but just a hunch.

Let me know if any other system or config info would be helpful to figure this out.

---

realize.yml file:
```
settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: 0.0.0.0
schema:
- name: appname
  path: .
  commands:
    fmt:
      status: true
    install:
      status: true
    run:
      status: true
  args:
  - service
  - run
  - --all
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
```

**Comment by Asoseil** [comment]
Could be related to #144

**Comment by jhartman86** [comment]
@Asoseil that sounds like the exact issue I'm seeing as well. Whatever I can do to contribute to helping resolve this, just let me know.

**Comment by Asoseil** [comment]
it would be great you could help, otherwise I'll check in the next days

**Comment by Asoseil** [comment]
could you retry after an update?

**Comment by jhartman86** [comment]
@Asoseil absolutely. just let me know when and what you want me to do

**Comment by Asoseil** [comment]
should be fixed with last master commit, let me know if it works, i have no more problems on macos

**Comment by jhartman86** [comment]
@Asoseil didn't seem to work. deleted realize from the /src directory and the installed binary from /bin, then reinstalled via `go get`, and confirmed the latest commit hash was `a039601914fae96a926fed72b0d5380773f6ff56`. can you confirm that should include the fix?

That said - the prompt response doesn't go unappreciated; much obliged for the quick turnaround. Lmk if I can provide any other info to help with this. Still planning to use (and recommend) realize for all projects going forward.

**Comment by Asoseil** [comment]
Try in this way:
```
go get -u github.com/tockins/realize
```
enable debug in your realize config

```
settings:
  recovery:
    events: true
    tools: false
  legacy:
```
post the logs after each change as #144

**Comment by jhartman86** [comment]
Ran `go get` with the `-u` flag and updated the config file per your suggestion. Same issue still seems to be occurring. By the events logged, it seems like its aware of the changes to a file after the first save, its just not restarting the app.

Explanation:
1. Realize was started, with updated configs
2. `...main.go` file was changed, which triggers a rebuild successfully
3. Same `main.go` file was changed again, which should have triggered rebuild, but didn't (although an event is detected and logged). This was done a couple times, hence the reason there are a few events after the second rebuild.
4. A different file was changed, which successfully triggers a rebuild.

Lmk if you want any more specific instructions followed for testing this.

```
jgh:conduit jon$ ~/go/bin/realize start
[09:59:58][CONDUIT] : Watching 114 file/s 60 folder/s[09:59:58][CONDUIT] : Install started
[10:00:00][CONDUIT] : Install completed in 2.183 s[10:00:00][CONDUIT] : Running..[10:00:00][CONDUIT] : 2018/01/10 10:00:00 -- DEV HELPER ROUTES ENABLED --
[10:00:00][CONDUIT] : [INF] Starting web service(s) on :[10:00:10]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile:  Time: 2018-01-10 10:00:10.350551 -0700 MST m=+12.229107328 LastTime: 0001-01-01 00:00:00 +0000 UTC
[10:00:10]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile:  Time: 2018-01-10 10:00:10.350755 -0700 MST m=+12.229311196 LastTime: 0001-01-01 00:00:00 +0000 UTC[10:00:10][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[10:00:10][CONDUIT] : Install started
[10:00:11]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.
com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:11.159459 -0700 MST m=+13.038048807 LastTime: 2018-01-10 10:00:10 -0700 MST[10:00:12][CONDUIT] : Install completed in 1.752 s[10:00:12][CONDUIT] : Running..
[10:00:12][CONDUIT] : 2018/01/10 10:00:12 -- DEV HELPER ROUTES ENABLED --
[10:00:12][CONDUIT] : [INF] Starting web service(s) on :
[10:00:16]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.
com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:16.747055 -0700 MST m=+18.625878551 LastTime: 2018-01-10 10:00:10 -0700 MST
[10:00:18]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:18.109341 -0700 MST m=+19.988220644 LastTime: 2018-01-10 10:00:10 -0700 MST[10:00:21]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.
com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:21.876336 -0700 MST m=+23.755374013 LastTime: 2018-01-10 10:00:10 -0700 MST[10:00:23]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:23.548419 -0700 MST m=+25.427525697 LastTime: 2018-01-10 10:00:10 -0700 MST
[10:00:25]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:25.450068 -0700 MST m=+27.329255109 LastTime: 2018-01-10 10:00:10 -0700 MST[10:00:30]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.
com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:30.489755 -0700 MST m=+32.369152566 LastTime: 2018-01-10 10:00:10 -0700 MST
[10:00:38]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:38.785908 -0700 MST m=+40.665651688 LastTime: 2018-01-10 10:00:10 -0700 MST
[10:00:38]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 10:00:38.786121 -0700 MST m=+40.665864914 LastTime: 2018-01-10 10:00:10 -0700 MST
[10:00:38][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go
[10:00:38][CONDUIT] : Install started
[10:00:40]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/pkg/routing/routes/post/post.go Time: 2018-01-10 10:00:40.205457 -0700 MST m=+42.085259745 LastTime: 2018-01-10 10:00:38 -0700 MST
[10:00:40][CONDUIT] : Install completed in 2.163 s
[10:00:40][CONDUIT] : Running..
[10:00:40][CONDUIT] : 2018/01/10 10:00:40 -- DEV HELPER ROUTES ENABLED --
[10:00:40][CONDUIT] : [INF] Starting web service(s) on :
```

**Comment by Asoseil** [comment]
it's weird because at the second file change on the same file there are only chmod events and no write event. What editor are you using?
"Realize" ignore these events because the logic around a chmod is too variable

**Comment by jhartman86** [comment]
I noticed that as well. I'm using VSCode - let me try this with Vim or Nano and I'll post results back here in a few minutes.

**Comment by jhartman86** [comment]
Ok your suspicions about vscode seem to be correct, works just fine when editing with vim. Here are the logs, for the record:
```
[14:21:12][CONDUIT] : Watching 1 file/s 0 folder/s
[14:21:12][CONDUIT] : Install started
[14:21:12][CONDUIT] : Install completed in 0.271 s
[14:21:12][CONDUIT] : Running..
[14:21:12][CONDUIT] : 2018/01/10 14:21:12 -- DEV HELPER ROUTES ENABLED --
[14:21:12][CONDUIT] : [INF] Starting web service(s) on :
[14:21:18]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile:  Time: 2018-01-10 14:21:18.664182 -0700 MST m=+6.218608561 LastTime: 0001-01-01 00:00:00 +0000 UTC
[14:21:31]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile:  Time: 2018-01-10 14:21:31.120796 -0700 MST m=+18.675765320 LastTime: 0001-01-01 00:00:00 +0000 UTC
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go~": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go~ LastFile:  Time: 2018-01-10 14:21:36.753873 -0700 MST m=+24.309089255 LastTime: 0001-01-01 00:00:00 +0000 UTC
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": RENAME File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile:  Time: 2018-01-10 14:21:36.753923 -0700 MST m=+24.309139696 LastTime: 0001-01-01 00:00:00 +0000 UTC
[14:21:36][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[14:21:36][CONDUIT] : Install started
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:36.754441 -0700 MST m=+24.309656792 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:36.754573 -0700 MST m=+24.309788788 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go~": REMOVE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go~ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:36.754648 -0700 MST m=+24.309863750 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:36]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": REMOVE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:36.860102 -0700 MST m=+24.415322672 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:38]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:38.266319 -0700 MST m=+25.821601226 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:38][CONDUIT] : Install completed in 2.208 s
[14:21:38][CONDUIT] : Running..
[14:21:38][CONDUIT] : 2018/01/10 14:21:38 -- DEV HELPER ROUTES ENABLED --
[14:21:38][CONDUIT] : [INF] Starting web service(s) on :
[14:21:43]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:43.923169 -0700 MST m=+31.478698456 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:43]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:43.923633 -0700 MST m=+31.479162563 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:51]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:51.487007 -0700 MST m=+39.042866379 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go~": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go~ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.627941 -0700 MST m=+44.184024491 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": RENAME File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.627998 -0700 MST m=+44.184082172 LastTime: 2018-01-10 14:21:36 -0700 MST
[14:21:56][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[14:21:56][CONDUIT] : Install started
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.628447 -0700 MST m=+44.184530267 LastTime: 2018-01-10 14:21:56 -0700 MST
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.62856 -0700 MST m=+44.184643820 LastTime: 2018-01-10 14:21:56 -0700 MST
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go~": REMOVE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go~ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.628629 -0700 MST m=+44.184713122 LastTime: 2018-01-10 14:21:56 -0700 MST
[14:21:56]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": REMOVE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:56.73039 -0700 MST m=+44.286478588 LastTime: 2018-01-10 14:21:56 -0700 MST
[14:21:57]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 14:21:57.999869 -0700 MST m=+45.556012493 LastTime: 2018-01-10 14:21:56 -0700 MST
[14:21:58][CONDUIT] : Install completed in 1.752 s
[14:21:58][CONDUIT] : Running..
[14:21:58][CONDUIT] : 2018/01/10 14:21:58 -- DEV HELPER ROUTES ENABLED --
[14:21:58][CONDUIT] : [INF] Starting web service(s) on :
```

I'll see if theres a vscode config that can be changed to make this work and will post back here. Maybe a _known issues_ section in the docs would be a good place to put it.

**Comment by jhartman86** [comment]
@Asoseil got some more time to play around with this tonight (initially looking for a fix with vscode), but became convinced the problem is still there (and not isolated to just using vscode). I ran `realize start` again, this time editing the same file with VSCode, Sublime, Atom, and VIM. The only time a rebuild occurred was, again the first time the file is saved, then subsequently, only after editing with VIM. Interestingly, it seems like VIM created a side file (in the logs below, look for `.swp` and did either renamed it or removed the *.swp file, which triggered a build?). Either way, the problem still persist not only with VSCode, but also Sublime and Atom editors.

```
jgh:Conduit jon$ ~/go/bin/realize start
[23:41:10][CONDUIT] : Watching 1 file/s 0 folder/s
[23:41:10][CONDUIT] : Install started
[23:41:10][CONDUIT] : Install completed in 0.271 s
[23:41:10][CONDUIT] : Running..
[23:41:10][CONDUIT] : 2018/01/10 23:41:10 -- DEV HELPER ROUTES ENABLED --
[23:41:10][CONDUIT] : [INF] Starting web service(s) on :
[23:41:17]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile:  Time: 2018-01-10 23:41:17.953947 -0700 MST m=+7.404046063 LastTime: 0001-01-01 00:00:00 +0000 UTC
[23:41:17]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile:  Time: 2018-01-10 23:41:17.954112 -0700 MST m=+7.404211534 LastTime: 0001-01-01 00:00:00 +0000 UTC
[23:41:17][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[23:41:17][CONDUIT] : Install started
[23:41:18]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:18.092646 -0700 MST m=+7.542751342 LastTime: 2018-01-10 23:41:17 -0700 MST
[23:41:19][CONDUIT] : Install completed in 1.691 s
[23:41:19][CONDUIT] : Running..
[23:41:19][CONDUIT] : 2018/01/10 23:41:19 -- DEV HELPER ROUTES ENABLED --
[23:41:19][CONDUIT] : [INF] Starting web service(s) on :
[23:41:24]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:24.456065 -0700 MST m=+13.906455344 LastTime: 2018-01-10 23:41:17 -0700 MST
[23:41:24]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:24.456164 -0700 MST m=+13.906554447 LastTime: 2018-01-10 23:41:17 -0700 MST
[23:41:25]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:25.535212 -0700 MST m=+14.985649995 LastTime: 2018-01-10 23:41:24 -0700 MST
[23:41:32]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:32.570681 -0700 MST m=+22.021433876 LastTime: 2018-01-10 23:41:24 -0700 MST
[23:41:32]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:32.570868 -0700 MST m=+22.021620936 LastTime: 2018-01-10 23:41:24 -0700 MST
[23:41:33]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:33.317056 -0700 MST m=+22.767841861 LastTime: 2018-01-10 23:41:32 -0700 MST
[23:41:39]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:39.952947 -0700 MST m=+29.404029398 LastTime: 2018-01-10 23:41:32 -0700 MST
[23:41:39]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:39.953034 -0700 MST m=+29.404116942 LastTime: 2018-01-10 23:41:32 -0700 MST
[23:41:43]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:43.219196 -0700 MST m=+32.670424705 LastTime: 2018-01-10 23:41:39 -0700 MST
[23:41:43]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE|CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:43.219553 -0700 MST m=+32.670782339 LastTime: 2018-01-10 23:41:39 -0700 MST
[23:41:48]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:48.233302 -0700 MST m=+37.684755028 LastTime: 2018-01-10 23:41:39 -0700 MST
[23:41:54]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go~": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go~ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:54.955589 -0700 MST m=+44.407342611 LastTime: 2018-01-10 23:41:39 -0700 MST
[23:41:54]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": RENAME File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:54.955653 -0700 MST m=+44.407406933 LastTime: 2018-01-10 23:41:39 -0700 MST
[23:41:54][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[23:41:54][CONDUIT] : Install started
[23:41:54]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:54.956261 -0700 MST m=+44.408014612 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:41:54]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:54.95639 -0700 MST m=+44.408143262 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:41:55]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp": REMOVE File: /Users/jon/go/src/github.com/jhartman86/conduit/.main.go.swp LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:41:55.062701 -0700 MST m=+44.514459379 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:41:56][CONDUIT] : Install completed in 1.734 s
[23:41:56][CONDUIT] : Running..
[23:41:56][CONDUIT] : 2018/01/10 23:41:56 -- DEV HELPER ROUTES ENABLED --
[23:41:56][CONDUIT] : [INF] Starting web service(s) on :
[23:42:12]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:42:12.694382 -0700 MST m=+62.146928612 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:46:50]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/.idea": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/.idea LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:46:50.129335 -0700 MST m=+339.594286051 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:47:08]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_bak___": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_bak___ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:08.159551 -0700 MST m=+357.625308236 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:47:08]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_old___": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_old___ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:08.160068 -0700 MST m=+357.625824903 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:47:08]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": RENAME File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:08.160114 -0700 MST m=+357.625871444 LastTime: 2018-01-10 23:41:54 -0700 MST
[23:47:08][CONDUIT] : GO changed /Users/jon/go/src/github.com/jhartman86/conduit/main.go
[23:47:08][CONDUIT] : Install started
[23:47:08]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CREATE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:08.160536 -0700 MST m=+357.626293180 LastTime: 2018-01-10 23:47:08 -0700 MST
[23:47:08]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_bak___": RENAME|CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go___jb_bak___ LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:08.160619 -0700 MST m=+357.626376845 LastTime: 2018-01-10 23:47:08 -0700 MST
[23:47:09]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-10 23:47:09.840781 -0700 MST m=+359.306612986 LastTime: 2018-01-10 23:47:08 -0700 MST
[23:47:11][CONDUIT] : Install completed in 3.614 s
[23:47:11][CONDUIT] : Running..
[23:47:11][CONDUIT] : 2018/01/10 23:47:11 -- DEV HELPER ROUTES ENABLED --
[23:47:11][CONDUIT] : [INF] Starting web service(s) on :
[00:02:46]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-11 00:02:46.859451 -0700 MST m=+1296.366957431 LastTime: 2018-01-10 23:47:08 -0700 MST
[00:02:51]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-11 00:02:51.563942 -0700 MST m=+1301.071658150 LastTime: 2018-01-10 23:47:08 -0700 MST
[00:02:51]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": WRITE File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-11 00:02:51.564055 -0700 MST m=+1301.071771508 LastTime: 2018-01-10 23:47:08 -0700 MST
[00:02:51]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-11 00:02:51.579064 -0700 MST m=+1301.086780840 LastTime: 2018-01-11 00:02:51 -0700 MST
[00:02:53]Event: "/Users/jon/go/src/github.com/jhartman86/conduit/main.go": CHMOD File: /Users/jon/go/src/github.com/jhartman86/conduit/main.go LastFile: /Users/jon/go/src/github.com/jhartman86/conduit/main.go Time: 2018-01-11 00:02:53.203144 -0700 MST m=+1302.710932477 LastTime: 2018-01-11 00:02:51 -0700 MST
```

**Comment by Asoseil** [comment]
we have detected the issue and we are working to solve it

**Comment by Asoseil** [comment]
should be fixed with #157

**Comment by jhartman86** [comment]
@Asoseil confirmed that #157 fixes it. Kick ass award to you sir.
